Task is almost done I still have some problems
htmlacademy-react/1047897-guess-melody-5 pull request #5
Opened 2020-10-08 16:30 UTC by RomanDovgii

2020-10-08 16:36 UTC, RomanDovgii commented
Привет! Вроде бы все заработало и не имеет проблем со стороны пользователя, но в консоль стреляет: 

"checkPropTypes.js:20 Warning: Failed prop type: The prop `question.answers[0].musician` is marked as required in `MusicianQuestionScreen`, but its value is `undefined`."
"checkPropTypes.js:20 Warning: Failed prop type: The prop `question.answers[0].src` is marked as required in `GenreQuestionScreen`, but its value is `undefined`."

И понимаю, что ошибка пишет, будто question.answer[0].musician и question.answer[0].src имеют значения `undefined`, но не понимаю где, так как если выводить их в консоль в соответствующих объектах, то значения отличаются от undefined.

2020-10-09 10:05 UTC, balesniy commented
> И понимаю, что ошибка пишет, будто question.answer[0].musician и question.answer[0].src имеют значения `undefined`, но не понимаю где

в дев-роутах перепутаны вопросы, `export const questions = [{type: 'genre',` и потом `<MusicianQuestionScreen question={firstQuestion}`

2020-10-09 10:12 UTC, balesniy requested changes

2020-10-09 10:12 UTC, balesniy commented on src/components/app/app.jsx
> +  questions: PropTypes.array.isRequired
Д12. При использовании PropTypes сложные типы данных описаны максимально подробно

2020-10-09 10:12 UTC, balesniy commented on src/components/genre-question-screen/genre-question-screen.jsx
> +    type: PropTypes.oneOf([GameType.MUSICIAN, GameType.GENRE]).isRequired,
для GenreQuestionScreen подходит только GameType.GENRE

2020-10-09 10:12 UTC, balesniy commented on src/components/musician-question-screen/musician-question-screen.jsx
> +  constructor(props) {
лишний конструктор, да и сам класс, см Д11. Если в компоненте есть только метод render, то он переписан как Functional Component

2020-10-09 10:12 UTC, balesniy commented on src/mocks/questions.js
> +      return genres.reduce((accumulator, genreLocal) => {
это похоже на map

2020-10-09 15:57 UTC, RomanDovgii commented
К сожалению, так и не понял как качественно оптимизировать QuestionsType в ./src/components/types/types.js .  Код в .oneOfType идентичен тому, что есть в MusicianQuestioтType B GenreQuestionType. Я пробовал оборачивать их в PropTypes,Shape({}), но все равно получал ошибку, но уже с checker'ом. Если возможно, то можно подробно описать то как можно данный момент оптимизировать? 
К сожалению, нормальных статей по oneOfType я так и не смог найти, он часто упоминается, но вне конкретно данного контекста.

2020-10-09 16:12 UTC, balesniy commented on src/mocks/questions.js
> +      genres.map((genreLocal) => {
map нужен для преобразования массива, он обрабатывает один, возвращает другой, genreQuestions и genreQuestions.push лишние

2020-10-09 16:15 UTC, balesniy commented on src/components/types/types.js
> +    PropTypes.shape({
MusicianQuestionType.question

2020-10-10 07:39 UTC, merged